# We cannot enable container-based infrastructure for now since we need TeXlive
# from a PPA
#sudo: false

language: python
python:
    - "2.7"

before_install:
  # http://about.travis-ci.org/docs/user/build-configuration/#Installing-Packages-Using-apt
  # Get Trilinos.
  - sudo add-apt-repository -y ppa:texlive-backports/ppa
  - sudo add-apt-repository -y ppa:pylab/stable  # for scipy
  - sudo apt-get update -qq
  - sudo apt-get install python-tk python-nose
  - sudo apt-get install texlive-latex-base texlive-latex-extra texlive-pictures
  - sudo apt-get install liblapack-dev gfortran python-scipy  # for ImageHash

# virtualenv:
#   system_site_packages: true
# # install dependencies
# addons:
#   apt:
#     packages:
#       - python-tk
#       - python-nose
#       - texlive-latex-base
#       - texlive-latex-extra
#       - texlive-pictures

install:
  # Alternative: setup.py install.
  # Using pip makes sure that the package is pip-compatible, too.
  - pip install .
  - pip install coveralls
  - pip install matplotlib
  - pip install Wand
  - pip install Pillow
  # Use --no-deps for ImageHash to avoid a lengthy install of scipy here.
  - pip install --no-deps ImageHash

# run tests
script:
  - python -c "import scipy; print(scipy.__file__); import scipy.fftpack"
  - nosetests #--with-coverage --cover-package=matplotlib2tikz
#after_success:
#  - coveralls
