# We cannot enable container-based infrastructure for now since we need TeXlive
# from a PPA
#sudo: false

language: python
python:
    - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - sudo add-apt-repository -y ppa:texlive-backports/ppa
  - sudo add-apt-repository -y ppa:pylab/stable  # for scipy
  - sudo apt-get update -qq
  - sudo apt-get install python-tk python-nose
  - sudo apt-get install texlive-latex-base texlive-latex-extra
    # texlive-latex-extra texlive-pictures
  - sudo apt-get install python-scipy  # for ImageHash
  - sudo apt-get install lua5.2  # for pgfplots

install:
  # Alternative: setup.py install.
  # Using pip makes sure that the package is pip-compatible, too.
  - pip install .
  - pip install coveralls
  - pip install matplotlib
  - pip install Wand
  - pip install Pillow
  - pip install ImageHash

# manually install important TeX dependencies
before_script:
  - export TEXMFLOCAL=/tmp/texmf/ && mkdir -p $TEXMFLOCAL
  - wget http://mirrors.ctan.org/install/graphics/pgf/base/pgf.tds.zip -O /tmp/pgf.zip
  - unzip /tmp/pgf.zip -d $TEXMFLOCAL
  - wget http://mirrors.ctan.org/install/graphics/pgf/contrib/pgfplots.tds.zip -O /tmp/pgfplots.zip
  - unzip /tmp/pgfplots.zip -d $TEXMFLOCAL
  - wget http://mirrors.ctan.org/install/macros/latex/contrib/standalone.tds.zip -O /tmp/standalone.zip
  - unzip /tmp/standalone.zip -d $TEXMFLOCAL
  - texhash

# run tests
script:
  - env
  - nosetests #--with-coverage --cover-package=matplotlib2tikz
#after_success:
#  - coveralls
