# We cannot enable container-based infrastructure for now since we need TeXlive
# from a PPA
#sudo: false

sudo: required
dist: trusty

language: python
python:
    - "2.7"
    - "3.4"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-nose2
  - sudo apt-get install texlive-latex-base texlive-latex-extra
  - sudo apt-get install python-scipy python3-scipy  # for ImageHash
  - sudo apt-get install poppler-utils
  - sudo apt-get build-dep python-matplotlib python3-matplotlib
  # Dependencies of Pillow, see
  # <https://pillow.readthedocs.org/en/latest/installation.html#linux-installation>.
  - sudo apt-get install libtiff5-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pyandoc
  # Alternative: setup.py install.
  # Using pip makes sure that the package is pip-compatible, too.
  - pip install .

# run tests
script:
  - nosetests --with-coverage --cover-package=matplotlib2tikz

after_success:
  - coveralls
